### ISSUE TITLE
Instant Crash on load model

### ISSUE THREAD

**Issue by michaelsakharov** [pipliz/cpuvox#2]
[Player.log](https://github.com/pipliz/cpuvox/files/4665299/Player.log)
Crash on loading a model, both in Editor but also using the Released version.

**Comment by pipliz** [comment]
This is with the included datasets from the release version, or some custom .obj ?
Crashing in "SimpleMesh:Rescale (single)" would probably be due to this line: https://github.com/pipliz/cpuvox/blob/master/Assets/Code/Utils/SimpleMesh.cs#L135 with a 0-vertices model

**Comment by pipliz** [comment]
The .obj's I'm loading look like this:  (txt instead of obj so it can attach here)
[bunny_lowres.txt](https://github.com/pipliz/cpuvox/files/4678517/bunny_lowres.txt)

**Comment by michaelsakharov** [comment]
I tried some custom ones which i modified the files to look like that, had the same crash.
I also used the default ones included in the release it also crashed.

**Comment by pipliz** [comment]
Hmm, interesting. Is this on unity 2019.3 as well?
Can you check the setting @ jobs->burst->native debug mode compilation, then crash the game, and check the editor log afterwards @ AppData\Local\Unity\Editor ?

**Comment by michaelsakharov** [comment]
2019.3.0f5, Crash happens using the release build as well so its not just my unity project/version.
<snip log>

**Comment by pipliz** [comment]
Removed the log from your comment (you never know with privacy stuff)

**Comment by pipliz** [comment]
It crashes with a

`=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================`

Which presumably means it's detecting a cpu feature badly and using instructions that aren't supported.

**Comment by pipliz** [comment]
One of the burst changelogs since the preview version it's using mentions:

> Fixed an issue where Burst was misidentifying F16C supporting CPUs as AVX2.

that could be related. I've updated it now on the master branch.

**Comment by michaelsakharov** [comment]
Awesome working now!
