### ISSUE TITLE
Wrong Lod?

### ISSUE THREAD

**Issue by michaelsakharov** [pipliz/cpuvox#5]
Hard to reproduce, but in some cases it seems the wrong LOD is used.
![image](https://user-images.githubusercontent.com/8621606/83310500-9094ac00-a24f-11ea-8d41-deddfc2dc013.png)

**Comment by pipliz** [comment]
I suspect it's the same as with https://github.com/pipliz/cpuvox/issues/3

**Comment by michaelsakharov** [comment]
Yup Fixed
